-- =========== QUESTION 1 ====================
-- Create table with name of emps based on employees table (with no data)
create table emps 
as select * from employees where 1 = 2;

-- populate the emps table using a select statement from the employees table for the employees in department 20.
insert into emps
select * from employees where department_id = 20

-- Add column Gender to table emps. ( int ), default 0 ; add comment on column ( 0 stands for Male, 1 stands for Female )
alter table emps
add gender int; 
comment on column emps.gender is '0 stands for male, 1 stands for female';
alter table emps
alter column gender set default 0;

-- =========== QUESTION 2 ====================
-- Create the DEPTS  table based on the following table instance chart.
-- COLUMN NAME | ID 	  |  NAME 
-- DATATYPE	   | Serial	| Varchar
-- LENGTH		   |        | 100
create table depts (
	id int generated by default as identity (start with 1 increment by 1),
	name varchar(100)
)

-- Populate the DEPTS table with data from departments table. Include only columns that you need. ( insert using sub query )
insert into depts
select department_id, department_name from departments;


-- Create table employee_bkp based on the structure of the employees table(Structure with data). 
-- Include only the employee_id, last_name, email, salary and department_id columns
create table employees_bkp
as select employee_id, last_name, email, salary, department_id from employees;


